vim.opt.clipboard = "unnamedplus" --Syncs Registers between OS and Nvim
vim.opt.tabstop = 2 -- Number of spaces that a <Tab> in the file counts for
vim.opt.softtabstop = 2 -- Number of spaces inserted for <Tab>
vim.opt.shiftwidth = 2 -- Number of spaces to use for auto-indenting
vim.opt.expandtab = true -- Convert tabs to spaces
vim.opt.autoindent = true -- Enable auto-indenting
vim.opt.smartindent = true -- Enable smart-indenting
vim.opt.ignorecase = true -- Ignore case when searching
vim.opt.smartcase = true -- Override 'ignorecase' if the search pattern contains upper case characters
vim.opt.hlsearch = true -- Highlight search results
vim.opt.incsearch = true -- Incremental searching
vim.opt.showmatch = true -- Show matching brackets
vim.opt.number = true -- Show line numbers
vim.opt.relativenumber = true -- Show relative line numbers
vim.opt.wrap = false -- Disable line wrapping
vim.opt.cursorline = true -- Highlight the current line
vim.opt.colorcolumn = "10000" -- Highlight column 80
vim.opt.backup = false -- Disable backup files
vim.opt.swapfile = false -- Disable swap files
vim.opt.splitright = true -- Split Verticals to Right
vim.opt.splitbelow = true -- split Horizontals to Below
